---
Document:
  index_documents_on_recording_session_id:
    RedundantIndexChecker:
      enabled: false
  index_documents_on_workspace_id:
    RedundantIndexChecker:
      enabled: false
Membership:
  index_memberships_on_user_id:
    RedundantIndexChecker:
      enabled: false
RecordingSession:
  document:
    MissingIndexChecker:
      enabled: false
  index_recording_sessions_on_workspace_id:
    RedundantIndexChecker:
      enabled: false
TransformerProfile:
  index_transformer_profiles_on_workspace_id:
    RedundantIndexChecker:
      enabled: false
  index_transformer_profiles_one_default_per_workspace:
    UniqueIndexChecker:
      enabled: false
User:
  password_digest:
    NullConstraintChecker:
      enabled: false
