inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - "db/schema.rb"
    - "db/cable_schema.rb"
    - "db/cache_schema.rb"
    - "db/queue_schema.rb"
    - "vendor/**/*"
    - "tmp/**/*"
    - "log/**/*"
    - "storage/**/*"
    - "app/assets/builds/**/*"
