#!/usr/bin/env ruby
# frozen_string_literal: true

require "fileutils"
require "pathname"
require "yaml"

ROOT = Pathname.new(__dir__).join("..").expand_path
SKILLS_ROOT = ROOT.join("skills")

def stringify_keys(value)
  case value
  when Hash
    value.each_with_object({}) { |(k, v), acc| acc[k.to_s] = stringify_keys(v) }
  when Array
    value.map { |item| stringify_keys(item) }
  else
    value
  end
end

def load_skill(skill_dir)
  manifest_path = skill_dir.join("manifest.yml")
  skill_md_path = skill_dir.join("skill.md")

  raise "Missing #{manifest_path}" unless manifest_path.file?
  raise "Missing #{skill_md_path}" unless skill_md_path.file?

  manifest = stringify_keys(YAML.safe_load(manifest_path.read, permitted_classes: [], aliases: true) || {})

  id = manifest["id"].to_s.strip
  name = manifest["name"].to_s.strip
  version = manifest["version"].to_s.strip
  summary = manifest.dig("instructions", "summary").to_s.strip
  steps = Array(manifest.dig("instructions", "steps")).map(&:to_s).map(&:strip).reject(&:empty?)
  compat = manifest.fetch("compat", {})

  raise "Invalid or missing id in #{manifest_path}" if id.empty?
  raise "Invalid or missing name in #{manifest_path}" if name.empty?
  raise "Invalid or missing version in #{manifest_path}" if version.empty?
  raise "Invalid or missing instructions.summary in #{manifest_path}" if summary.empty?
  raise "Missing compat.claude_agent in #{manifest_path}" if compat["claude_agent"].nil?
  raise "Missing compat.codex_skill in #{manifest_path}" if compat["codex_skill"].nil?

  entrypoints = Array(manifest["entrypoints"])
  entrypoints.each do |entrypoint|
    next unless entrypoint.is_a?(Hash) && entrypoint["type"].to_s == "script"

    path = entrypoint["path"].to_s
    next if path.empty?

    full_path = skill_dir.join(path)
    raise "Entrypoint script not found: #{full_path}" unless full_path.file?
  end

  {
    "id" => id,
    "name" => name,
    "version" => version,
    "summary" => summary,
    "steps" => steps,
    "compat" => compat,
    "entrypoints" => entrypoints,
    "skill_md" => skill_md_path.read,
    "skill_dir" => skill_dir
  }
end

def generated_source_notice(skill)
  "Source: /skills/#{skill.fetch("id")}/manifest.yml and /skills/#{skill.fetch("id")}/skill.md"
end

def claude_content(skill)
  frontmatter = {
    "name" => skill.fetch("id"),
    "description" => skill.fetch("summary")
  }

  yaml_body = YAML.dump(frontmatter).sub(/\A---\s*\n/, "").rstrip

  <<~MD
    ---
    # GENERATED FILE - DO NOT EDIT
    # #{generated_source_notice(skill)}
    #{yaml_body}
    ---

    #{skill.fetch("skill_md").rstrip}
  MD
end

def codex_openai_yaml(skill)
  default_prompt = if skill.fetch("steps").empty?
                     "Use this skill to #{skill.fetch("summary").downcase.sub(/\.$/, "")}."
  else
                     "Use this skill to: #{skill.fetch("steps").join(" ")}"
  end

  payload = {
    "interface" => {
      "display_name" => skill.fetch("name"),
      "short_description" => skill.fetch("summary"),
      "default_prompt" => default_prompt
    }
  }

  yaml_body = YAML.dump(payload).sub(/\A---\s*\n/, "")

  <<~YAML
    # GENERATED FILE - DO NOT EDIT
    # #{generated_source_notice(skill)}
    #{yaml_body}
  YAML
end

def codex_skill_md(skill)
  <<~MD
    <!-- GENERATED FILE - DO NOT EDIT -->
    <!-- #{generated_source_notice(skill)} -->

    #{skill.fetch("skill_md").rstrip}
  MD
end

def root_skill_index_md(skills)
  skill_lines = skills.map do |skill|
    id = skill.fetch("id")
    summary = skill.fetch("summary")
    "- `#{id}` (`.codex/skills/#{id}/SKILL.md`) - #{summary}"
  end.join("\n")

  <<~MD
    <!-- GENERATED FILE - DO NOT EDIT -->
    <!-- Source: /skills/*/manifest.yml and /skills/*/skill.md -->

    # Repo Skill Index

    This file is generated by `make skills`.
    Canonical skill sources live under `skills/`.

    Available generated Codex skills:

    #{skill_lines}
  MD
end

def write_file(path, content)
  FileUtils.mkdir_p(path.dirname)
  path.write(content)
end

def copy_scripts(skill, dest_dir)
  source_scripts = skill.fetch("skill_dir").join("scripts")
  return unless source_scripts.directory?

  files = source_scripts.children
  return if files.empty?

  FileUtils.mkdir_p(dest_dir)
  files.each do |file|
    FileUtils.cp_r(file.to_s, dest_dir.join(file.basename).to_s, preserve: true)
  end
end

def generate_into(output_root)
  output_root = Pathname.new(output_root)
  claude_root = output_root.join(".claude", "agents")
  codex_root = output_root.join(".codex", "skills")

  FileUtils.mkdir_p(claude_root)
  FileUtils.mkdir_p(codex_root)

  skill_dirs = SKILLS_ROOT.children.select(&:directory?).sort
  raise "No skills found in #{SKILLS_ROOT}" if skill_dirs.empty?

  skills = skill_dirs.map { |dir| load_skill(dir) }

  write_file(output_root.join("SKILL.md"), root_skill_index_md(skills))

  skills.each do |skill|
    id = skill.fetch("id")

    if skill.dig("compat", "claude_agent")
      write_file(claude_root.join("#{id}.md"), claude_content(skill))
    end

    if skill.dig("compat", "codex_skill")
      codex_skill_root = codex_root.join(id)
      write_file(codex_skill_root.join("SKILL.md"), codex_skill_md(skill))
      write_file(codex_skill_root.join("agents", "openai.yaml"), codex_openai_yaml(skill))
      copy_scripts(skill, codex_skill_root.join("scripts"))
    end
  end
end

if ARGV.length != 1
  warn "Usage: #{$PROGRAM_NAME} <output-root>"
  exit 1
end

generate_into(ARGV.fetch(0))
